#!/usr/bin/env python3
"""
Build script to generate RAMFS file table from initfs/ directory.

This script scans the initfs/ directory recursively and generates:
- ramfs_generated.h: extern declarations for file symbols
- ramfs_generated.c: file table array with entries for each file

Usage:
    ./scripts/generate_ramfs_table.py --source-dir VinixOS/initfs/ \
        --output-header kernel/ramfs_generated.h \
        --output-source kernel/ramfs_generated.c
"""

import os
import sys
import argparse
import re


def filename_to_symbol(filepath, source_dir):
    """
    Convert a file path to a C symbol name.
    
    Args:
        filepath: Full path to the file
        source_dir: Base source directory to strip from path
    
    Returns:
        Symbol name (e.g., "hello_txt" for "hello.txt")
    
    Raises:
        ValueError: If the filename cannot be converted to a valid C identifier
    """
    # Get relative path from source directory
    rel_path = os.path.relpath(filepath, source_dir)
    
    # Replace path separators, dots, and dashes with underscores
    symbol = rel_path.replace(os.sep, '_').replace('.', '_').replace('-', '_')
    
    # Validate that result is a valid C identifier
    # C identifier: starts with letter or underscore, followed by letters, digits, or underscores
    if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', symbol):
        raise ValueError(f"Cannot convert filename '{rel_path}' to valid C identifier")
    
    return symbol


def generate_header(files, source_dir, output_path):
    """
    Generate ramfs_generated.h with extern declarations.
    
    Args:
        files: List of file paths to include
        source_dir: Base source directory
        output_path: Path to write the header file
    """
    lines = []
    lines.append("#ifndef RAMFS_GENERATED_H")
    lines.append("#define RAMFS_GENERATED_H")
    lines.append("")
    lines.append("#include \"ramfs.h\"")
    lines.append("")
    lines.append("/* File symbols generated by build script */")
    
    # Generate extern declarations for each file
    for filepath in files:
        try:
            symbol = filename_to_symbol(filepath, source_dir)
            lines.append(f"extern uint8_t _ramfs_{symbol}_start[];")
            lines.append(f"extern uint8_t _ramfs_{symbol}_end[];")
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    
    lines.append("")
    lines.append("/* Generated file table and metadata */")
    lines.append("extern struct ramfs_file ramfs_file_table[];")
    lines.append("extern const uint8_t *ramfs_file_end_table[];")
    lines.append("extern const uint32_t ramfs_file_count;")
    lines.append("")
    lines.append("#endif /* RAMFS_GENERATED_H */")
    lines.append("")
    
    # Write to file
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated header: {output_path}")


def generate_source(files, source_dir, output_path):
    """
    Generate ramfs_generated.c with file table array.
    
    Args:
        files: List of file paths to include
        source_dir: Base source directory
        output_path: Path to write the source file
    """
    lines = []
    lines.append("#include \"ramfs_generated.h\"")
    lines.append("")
    lines.append("/* Generated file table */")
    lines.append("struct ramfs_file ramfs_file_table[] = {")
    
    # Generate entry for each file
    for filepath in files:
        try:
            symbol = filename_to_symbol(filepath, source_dir)
            # Get relative path from source directory for the name field
            rel_path = os.path.relpath(filepath, source_dir)
            
            lines.append("    {")
            lines.append(f"        .name = \"{rel_path}\",")
            lines.append(f"        .data = _ramfs_{symbol}_start,")
            lines.append(f"        .size = 0  /* Computed at runtime in ramfs_init() */")
            lines.append("    },")
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    
    lines.append("};")
    lines.append("")
    
    # Generate end pointer table for size computation
    lines.append("/* End pointers for size computation */")
    lines.append("const uint8_t *ramfs_file_end_table[] = {")
    for filepath in files:
        try:
            symbol = filename_to_symbol(filepath, source_dir)
            lines.append(f"    _ramfs_{symbol}_end,")
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    lines.append("};")
    lines.append("")
    
    lines.append(f"const uint32_t ramfs_file_count = {len(files)};")
    lines.append("")
    
    # Write to file
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated source: {output_path}")


def generate_assembly(files, source_dir, output_path):
    """
    Generate assembly file with .incbin directives for each file.
    
    Args:
        files: List of file paths to include
        source_dir: Base source directory
        output_path: Path to write the assembly file
    """
    lines = []
    lines.append("/* AUTO-GENERATED FILE - DO NOT EDIT */")
    lines.append("/* Generated by scripts/generate_ramfs_table.py */")
    lines.append("")
    lines.append(".syntax unified")
    lines.append(".section .rodata")
    lines.append("")
    lines.append("/* ============================================================")
    lines.append(" * RAMFS Embedded Files")
    lines.append(" * ============================================================ */")
    lines.append("")
    
    # Generate .incbin directive for each file
    for filepath in files:
        try:
            symbol = filename_to_symbol(filepath, source_dir)
            rel_path = os.path.relpath(filepath, source_dir)
            
            lines.append(f"/* {rel_path} */")
            lines.append(f".global _ramfs_{symbol}_start")
            lines.append(f".global _ramfs_{symbol}_end")
            lines.append(".align 4")
            lines.append(f"_ramfs_{symbol}_start:")
            lines.append(f'    .incbin "{filepath}"')
            lines.append(f"_ramfs_{symbol}_end:")
            lines.append("")
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    
    # Write to file
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated assembly: {output_path}")


def main():
    """Main entry point for the build script."""
    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description='Generate RAMFS file table from source directory'
    )
    parser.add_argument(
        '--source-dir',
        required=True,
        help='Source directory containing files to embed (e.g., VinixOS/initfs/)'
    )
    parser.add_argument(
        '--output-header',
        required=True,
        help='Output path for generated header file (e.g., kernel/ramfs_generated.h)'
    )
    parser.add_argument(
        '--output-source',
        required=True,
        help='Output path for generated source file (e.g., kernel/ramfs_generated.c)'
    )
    parser.add_argument(
        '--output-assembly',
        required=False,
        help='Output path for generated assembly file (e.g., kernel/ramfs_payload.S)'
    )
    
    args = parser.parse_args()
    
    # Validate source directory exists
    if not os.path.exists(args.source_dir):
        print(f"Error: Source directory '{args.source_dir}' not found", file=sys.stderr)
        sys.exit(1)
    
    if not os.path.isdir(args.source_dir):
        print(f"Error: Source path '{args.source_dir}' is not a directory", file=sys.stderr)
        sys.exit(1)
    
    # Scan directory for all files
    files = []
    for root, dirs, filenames in os.walk(args.source_dir):
        for filename in filenames:
            file_path = os.path.join(root, filename)
            
            # Check if file is readable (requirement 5.2)
            if not os.access(file_path, os.R_OK):
                print(f"Error: Cannot read file '{file_path}': Permission denied", file=sys.stderr)
                sys.exit(1)
            
            # Try to actually read the file to catch other read errors
            try:
                with open(file_path, 'rb') as f:
                    # Just check if we can open it, don't read content yet
                    pass
            except IOError as e:
                print(f"Error: Cannot read file '{file_path}': {e.strerror}", file=sys.stderr)
                sys.exit(1)
            except Exception as e:
                print(f"Error: Cannot read file '{file_path}': {str(e)}", file=sys.stderr)
                sys.exit(1)
            
            files.append(file_path)
    
    print(f"Found {len(files)} file(s) in {args.source_dir}")
    
    # Check for duplicate symbol names after conversion (requirement 5.3)
    symbol_map = {}
    for filepath in files:
        try:
            symbol = filename_to_symbol(filepath, args.source_dir)
            if symbol in symbol_map:
                # Found duplicate - report both files
                original_file = symbol_map[symbol]
                rel_path1 = os.path.relpath(original_file, args.source_dir)
                rel_path2 = os.path.relpath(filepath, args.source_dir)
                print(f"Error: Duplicate filename after symbol conversion:", file=sys.stderr)
                print(f"  '{rel_path1}' and '{rel_path2}' both convert to symbol '_ramfs_{symbol}'", file=sys.stderr)
                sys.exit(1)
            symbol_map[symbol] = filepath
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    
    # Generate header file
    generate_header(files, args.source_dir, args.output_header)
    
    # Generate source file
    generate_source(files, args.source_dir, args.output_source)
    
    # Generate assembly file if requested
    if args.output_assembly:
        generate_assembly(files, args.source_dir, args.output_assembly)
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
