sequenceDiagram
    participant U as User_Task
    participant H as CPU_Hardware
    participant V as Vector_Table
    participant S as Entry_Stub_ASM
    participant K as Kernel_C_Handler

    Note over U: User calls Syscall
    U->>H: SVC 0
    
    Note over H: [Hardware Logic]
    Note over H: CPSR -> SPSR_svc, PC -> LR_svc
    H->>V: Jump to VBAR + 0x08
    
    Note over V: [Vector Table]
    V->>S: b exception_entry_svc
    
    activate S
    Note over S: [Save Context]
    Note over S: stmfd sp!, {r0-r12, lr}
    Note over S: mrs r0, spsr
    Note over S: stmfd sp!, {r0, r1}
    
    Note over S: [Pass Params & Call]
    S->>K: svc_handler(regs)
    activate K
    
    Note right of K: Dispatching...
    
    K-->>S: return R0
    deactivate K
    
    Note over S: [Restore SPSR]
    Note over S: ldmfd sp!, {r0, r1}
    Note over S: msr spsr, r0
    
    rect rgb(240, 240, 255)
    Note over S, H: [Critical: System Mode Switch]
    S->>H: cps 0x1F (System Mode)
    Note over H: Access/Fix SP_usr
    H->>S: cps 0x13 (SVC Mode)
    end
    
    Note over S: [Final Return]
    Note over S: ldmfd sp!, {r0-r12, pc}^
    S->>U: Resume User Task
    deactivate S